
name: Build Tick on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  KLOG: 3
  TICK_DEBUG: 0
  MKN_CL_PREFERRED: 1

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: windows-2022

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    # setup MSVC compiler
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - run: |
        swig -version
        pip install pip --upgrade
        pip install wheel
        pip install -r requirements.txt

    - name: Build
      shell: cmd
      run: | # /bin/link interferes with cl/link.exe
        bash -c 'rm /bin/link'
        bash -c 'curl -Lo mkn.exe https://github.com/mkn/mkn/releases/download/latest/mkn.exe'
        bash -c 'set -ex; export PATH="$PWD:$PATH" KLOG=3; ./sh/mkn.sh'

    - name: cpp_test
      shell: cmd
      run: |
        bash -c 'set -ex; export PATH="$PWD:$PATH" KLOG=3; ./sh/gtest.sh'

    - name: py_test
      shell: cmd
      run: |
        bash -c 'PYTHONPATH=$PWD python3 -m unittest discover -v . "*_test.py"'
