
name: Build Tick on OSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: info
      run: |
        swig -version

    - name: pip
      run: |
        pip install wheel pip --upgrade
        pip install -r requirements.txt

    - name: info
      run: |
        swig -version

    - name: build
      run: |
        python setup.py build_ext --inplace

    - name: test
      run: |
        python setup.py cpptest
        python -m unittest discover -v . "*_test.py"
