
name: Build Tick on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  KLOG: 3
  TICK_DEBUG: 0


jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.10']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - run: |
        swig -version

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        python3 -m pip install wheel pip --upgrade
        python3 -m pip install -r requirements.txt

    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        sudo cp mkn /usr/bin
        ./sh/mkn.sh
        ./sh/gtest.sh
        python3 setup.py pytest
