
name: Build Tick on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0


jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.10']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install gtest
      # release-1.12.1 == last C++11 release
      run: |
        git clone https://github.com/google/googletest -b release-1.12.1
        (cd googletest && mkdir build && cd build && cmake .. && make && sudo make install)
        rm -rf googletest

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: info
      run: |
        gcc -v
        swig -version

    - name: pip
      run: |
        python3 -m pip install wheel pip --upgrade
        python3 -m pip install -r requirements.txt

    - name: build
      run: |
        python3 setup.py build_ext --inplace

    - name: cpptest
      run: |
        python3 setup.py cpptest

    - name: pytest
      run: |
        python3 setup.py pytest
