
name: Build Tick on OSX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TICK_DEBUG: 0
  TICK_WERROR: 0

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install swig
      run: |
        brew update
        brew install automake m4
        git clone https://github.com/swig/swig -b rel-4.0.2 swig
        (cd swig && ./autogen.sh && ./configure --without-pcre && make && make install)
        rm -rf swig

    # - name: install gtest
    #   run: |
    #     git clone https://github.com/google/googletest --depth 1 gtest
    #     (cd gtest && mkdir -p build && cd build && cmake .. && make && make install)
    #     rm -rf gtest

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        pip install pip --upgrade
        pip install wheel
        pip install -r requirements.txt

    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_osx
        chmod +x mkn
        export PATH="$PWD:$PATH"
        ./sh/mkn.sh
        ./sh/gtest.sh
        python -m unittest discover -v . "*_test.py"
